name: Python package

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - .pre-commit-config.yaml
  pull_request:
  release:
    types:
    - published

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        python -m pip install -U black isort flake8 bandit[toml]
    - run: python -m black . --check
    - run: python -m isort . --check-only
    - run: python -m flake8 .
    - run: python -m bandit . --recursive -c pyproject.toml

  test-py310-minus:
    needs: lint
    strategy:
      matrix:
        os: [windows-latest, ubuntu-22.04, macos-13]
        python-version: ['3.8', '3.9', '3.10']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        python -m pip install uv
        python -m uv run --extra qt5 -m pytest

  test-py311-plus:
    needs: lint
    strategy:
      matrix:
        os: [windows-latest, macos-14]
        python-version: ['3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        python -m pip install uv
        python -m uv run --extra qt6 -m pytest

  test-py311-plus-ubuntu:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-22.04]
        python-version: ['3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build
      run: |
        sudo apt install libegl1
        python -m pip install uv
        python -m uv run --extra qt6 -m pytest

  build-and-deploy:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: [test-py310-minus, test-py311-plus, test-py311-plus-ubuntu]
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.8
    - name: Build
      run: |
        python -m pip install -U pip build wheel
        python -m build .
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
