name: Python package

on:
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'
    paths-ignore:
    - .pre-commit-config.yaml
  pull_request:
  release:
    types:
    - published

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip wheel
        python -m pip install -U black isort flake8 bandit
    - run: python -m black . --check
    - run: python -m isort . --check-only
    - run: python -m flake8 .
    - run: python -m bandit . --recursive -c pyproject.toml

  build-and-deploy:
    if: github.event_name == 'release' && github.event.action == 'published'
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Build
      run: |
        python -m pip install -U pip build wheel
        python -m build . --wheel --sdist
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
